version: '3.8'

networks:
  shop_default:
    driver: overlay

services:
  frontend:
    image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
    ports:
      - "80:8080"
    environment:
      - PORT=8080
      - AD_SERVICE_ADDR=adservice:9555
      - CART_SERVICE_ADDR=cartservice:7070
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
    networks:
      - shop_default
    deploy:
      replicas: 1

  currencyservice:
    image: gcr.io/google-samples/microservices-demo/currencyservice:v0.8.0
    environment:
      - PORT=7000
      - DISABLE_PROFILER=true
    networks:
      - shop_default
    deploy:
      replicas: 1

  cartservice:
    image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
    networks:
      - shop_default
    deploy:
      replicas: 1

  productcatalogservice:
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
    networks:
      - shop_default
    deploy:
      replicas: 1

  redis:
    image: redis:alpine
    networks:
      - shop_default
    deploy:
      replicas: 1
